namespace DomainLibrary.Constants
{
    public static class LogSteps
    {
        public const string EXCEPTION = "EXCEPTION";

        // Users steps
        public const string GET_USER_BY_ID = "GET_USER_BY_ID";
        public const string CREATE_NEW_USER = "CREATE_NEW_USER";
        public const string EDIT_USER_BY_ID = "EDIT_USER_BY_ID";
        public const string DELETE_USER_BY_ID = "DELETE_USER_BY_ID";
        public const string USER_VALIDATION_ERROR = "USER_VALIDATION_ERROR";

        // Products steps
        public const string GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
        public const string CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
        public const string EDIT_PRODUCT_BY_ID = "EDIT_PRODUCT_BY_ID";
        public const string DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
        public const string PRODUCT_VALIDATION_ERROR = "PRODUCT_VALIDATION_ERROR";

        // Subscriptions steps
        public const string GET_SUBSCRIPTION_BY_ID = "GET_SUBSCRIPTION_BY_ID";
        public const string CREATE_NEW_SUBSCRIPTION = "CREATE_NEW_SUBSCRIPTION";
        public const string EDIT_SUBSCRIPTION_BY_ID = "EDIT_SUBSCRIPTION_BY_ID";
        public const string DELETE_SUBSCRIPTION_BY_ID = "DELETE_SUBSCRIPTION_BY_ID";
        public const string SUBSCRIPTION_VALIDATION_ERROR = "SUBSCRIPTION_VALIDATION_ERROR";

        // Services steps
        public const string USER_SERVICE_CREATE_USER_PROCESSING = "USER_SERVICE_CREATE_USER_PROCESSING";
        public const string USER_SERVICE_RETRIEVE_USER_PROCESSING = "USER_SERVICE_RETRIEVE_USER_PROCESSING";
        public const string USER_SERVICE_DELETE_USER_PROCESSING = "USER_SERVICE_DELETE_USER_PROCESSING";
        public const string USER_SERVICE_UPDATE_USER_PROCESSING = "USER_SERVICE_UPDATE_USER_PROCESSING";

        public const string PRODUCT_SERVICE_CREATE_PRODUCT_PROCESSING = "PRODUCT_SERVICE_CREATE_PRODUCT_PROCESSING";
        public const string PRODUCT_SERVICE_RETRIEVE_PRODUCT_PROCESSING = "PRODUCT_SERVICE_RETRIEVE_PRODUCT_PROCESSING";
        public const string PRODUCT_SERVICE_DELETE_PRODUCT_PROCESSING = "PRODUCT_SERVICE_DELETE_PRODUCT_PROCESSING";
        public const string PRODUCT_SERVICE_UPDATE_PRODUCT_PROCESSING = "PRODUCT_SERVICE_UPDATE_PRODUCT_PROCESSING";

        public const string SUBSCRIPTION_SERVICE_CREATE_SUBSCRIPTION_PROCESSING = "USER_SERVICE_CREATE_SUBSCRIPTION_PROCESSING";
        public const string SUBSCRIPTION_SERVICE_RETRIEVE_SUBSCRIPTION_PROCESSING = "USER_SERVICE_RETRIEVE_SUBSCRIPTION_PROCESSING";
        public const string SUBSCRIPTION_SERVICE_DELETE_SUBSCRIPTION_PROCESSING = "USER_SERVICE_DELETE_SUBSCRIPTION_PROCESSING";
        public const string SUBSCRIPTION_SERVICE_UPDATE_SUBSCRIPTION_PROCESSING = "USER_SERVICE_UPDATE_SUBSCRIPTION_PROCESSING";

        // Database steps
        public const string USER_DATABASE_RETRIEVE_DATA = "USER_DATABASE_RETRIEVE_DATA";
        public const string USER_DATABASE_CREATE_DATA = "USER_DATABASE_CREATE_DATA";
        public const string USER_DATABASE_UPDATE_DATA = "USER_DATABASE_UPDATE_DATA";
        public const string USER_DATABASE_DELETE_DATA = "USER_DATABASE_DELETE_DATA";

        public const string PRODUCT_DATABASE_RETRIEVE_DATA = "PRODUCT_DATABASE_RETRIEVE_DATA";
        public const string PRODUCT_DATABASE_CREATE_DATA = "PRODUCT_DATABASE_CREATE_DATA";
        public const string PRODUCT_DATABASE_UPDATE_DATA = "PRODUCT_DATABASE_UPDATE_DATA";
        public const string PRODUCT_DATABASE_DELETE_DATA = "PRODUCT_DATABASE_DELETE_DATA";

        public const string SUBSCRIPTION_DATABASE_RETRIEVE_DATA = "SUBSCRIPTION_DATABASE_RETRIEVE_DATA";
        public const string SUBSCRIPTION_DATABASE_CREATE_DATA = "SUBSCRIPTION_DATABASE_CREATE_DATA";
        public const string SUBSCRIPTION_DATABASE_UPDATE_DATA = "SUBSCRIPTION_DATABASE_UPDATE_DATA";
        public const string SUBSCRIPTION_DATABASE_DELETE_DATA = "SUBSCRIPTION_DATABASE_DELETE_DATA";
    }
}
